### ISSUE TITLE
楼主大大,我外层想绘制一个带渐变颜色的圆环

### ISSUE THREAD

**Issue by qiuseruxin** [zssr/CircularProgressView#2]

**Comment by qiuseruxin** [comment]
能教我一下怎么弄吗

**Comment by swif2** [comment]
https://gist.github.com/boredzo/5691822   可以参考这个

https://developer.apple.com/library/content/documentation/GraphicsImaging/Conceptual/drawingwithquartz2d/dq_shadings/dq_shadings.html
